# Generated by Django 4.1.7 on 2023-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_cart_items_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='ia_active',
            new_name='is_active',
        ),
    ]
