# Generated by Django 4.1.7 on 2023-04-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variation'),
        ('carts', '0003_rename_ia_active_cartitems_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variation',
            field=models.ManyToManyField(blank=True, to='products.variation'),
        ),
    ]
